sudo: required
language: ruby
services:
- docker
env:
  global:
    secure: b+Bx7j2hZDMlf+gu2jxt5dJ3VcECB7tuIIlK9yq2RAziEKosFptvkE/dkpQVAccSImYKm6RY7cKo9NcehBADSO9Q1bIbARJMhc+Me2lVZuIx4Uw1yC4VH7stBcYGvqPN21l3W4Suqmjzd9vximw7GW316YGdICcHMAk7IVByTWfnlTbjCS7Tyd1UBkkMqXBkBhGDPr5b5/RuybPzrPANkKHy5CuYSpbARPuIVCR/8fNQHJDC8l71Bnuk29EF2tpTam4z43Rjy0o2bLkH0JtNX1S6sTQ7YqRsDmgUdAMeVX8RR8ZeW5QfQi7xrB9fnKh9a1ZmQQWpqgvI4+YcK3JbH5wk4St8CTtm/Ku9VNI9O3eJqClIfc6a2hqe+1jYYKZWjDDJ8EOjGdbOfhFTR9mYwdrRg59yDM5WmyM16If+EkpIazE84GlIMtzff8S56ZlaW78encxZaj0ZS4CDbrmj/CHcByeFw2XnaSIlVmJTFlbY6ULzH+9tvVYwxCBXppxyFDYpLRdZ7zmF4X/7Z8p8RNzMRE5sGyD1mLFQjLnhFMtlJlsGzV0yzxnXw4GyYSVMbQe4fLL71IQy9fqgZIIR4+iiAH+cO5BhAdMeeq8N3oyziSHy9UTTT+zEq+36ldvhw2aN0Mbe1oQtuMNPizu6iUqD8cfaoaT8iNMz1IPZ80k=
before_install:
- echo $dockerhub_username | cat
- echo "$dockerhub_password" | docker login --username "$dockerhub_username" --password-stdin
script: bash docker_push
