sudo: required
language: ruby
services:
- docker
env:
  global:
    secure: EV4BRpIPmKMNI3zHGwubBd12lEdlR2soI1X3CuJIMZtXeXtnIRS/vq14aCmRuZu8+m/W7ksJfVnly2nzNR62mDtFgQjzkyei19p/o0tQeFcK2fpkXqcgMc0CKmm9Orl8EXyctIrkRlpDAQsHreTtF/6jidDnqMSdCbNOtiw7YNbTdC7IJCCZofharFBU/yqlutN9i+cxllf60Gq4D2PH+8uscvlkiv3GrnIoqDBfEsMlRSQwlS3zo/+qYT9gmWUNIctSP9GmDoQGKM5kwbK4lE6OHAsJZB2EeNFAyO7b7H0Dip7UwUyXvjqwNIAuMLFlmROn8AMzZ3GK0FbESq/ulfVUbkHWnWiXgJG8fOIKPp7a2rwfnq+p1yP4JNUISWcunPKokfj08Gonkb5by9BdPGWFRqF2ojX2ni9ttNb66+gmvVah/T3YWTWfgKSydj9idMm+cvrn55yrF7+ySJvsD/+S2u1d4xV3b2dvmCujkxqRshz/wF33tpXGAERWezIjxr2x2dvtwCc3afROzqAlytbhUKb5yRtszyC/UeXYq6TESsxsbOo77KE3BGXG5mYek8ixAY/8SzBEB58m5x9BQ9ZVCMfLxiNgdes8LBaAPO/I1LXK9/qu9M1MTOlV4DjcSCRLO8hsDgoP7Qmm5YYXvOc8gbTMzK/tA90R10koIpA=
script: bash docker_push
